config/routes.rb
Rails.application.routes.draw do
  resources :careers
  
  match '/addcareer',  to: 'careers#new',            via: 'get'
  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/career.rb
class Career < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  def new
  	@career = Career.new
  end

  def show
  	@career = Career.find(params[:id])
  end

  def create
    @career = Career.new(career_params)
    @career.save
    redirect_to @career
  end

  private

    def career_params
      params.require(:career).permit(:name, :school_length)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/careers/new.html.erb
<% content_for :title, "New Career" %>

<h1>Add a New Career</h1>

<div class="row">
	<div class="large 6-columns">
		<form>
			<%= form_for(@career) do |c| %>

		      <%= c.label :name %>
		      <%= c.text_field :name %>

		      <%= c.label :school_length %>
		      <%= c.text_field :school_length %>

		      <%= c.submit "Add Career", class: "button" %>
		    <% end %>
		</form>
	</div>
</div>

app/views/careers/show.html.erb
<h1><%= @career.name %></h1>

<p><b>School length:</b> <%= @career.school_length%></p>

app/views/layouts/_topmenu.html.erb
  <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">My Site</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Add Career", addcareer_path %></li>
      <li><%= link_to "Contact Us", contact_path %></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
 <%= render 'layouts/topmenu' %>

<div class="row">
  <div class="large 12-columns">
      <%= yield %>
  </div>
</div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>Contact Us</h1>

<p>Use this form to get in touch with us!</p>

<form>
  <fieldset>
    <legend>Contact</legend>

    <label>Input Label
      <input type="text" placeholder="Inputs and other form elements go inside...">
    </label>
  </fieldset>
</form>

app/views/static_pages/help.html.erb
<% content_for :title, "Help" %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% content_for :title, "Home" %>
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>